install/update homebrew on macos before installing packages

diff --git a/run_onchange_before_install-packages-darwin.sh.tmpl b/run_onchange_before_install-packages-darwin.sh.tmpl
--- a/run_onchange_before_install-packages-darwin.sh.tmpl
+++ b/run_onchange_before_install-packages-darwin.sh.tmpl
@@ -1,5 +1,16 @@
 {{- if eq .chezmoi.os "darwin" -}}
-#!/bin/bash
+#!/bin/zsh
+
+# install/update homebrew
+which -s brew
+if [[ $? != 0 ]] ; then
+  echo "Homebrew not found. Installing..."
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+else
+  echo "Homebrew already installed. Updating..."
+  brew update
+  brew upgrade
+fi
 
 brew bundle --no-lock --file=/dev/stdin <<EOF
 tap "homebrew/cask-fonts"
@@ -18,6 +29,7 @@ brew "starship"
 brew "tmux"
 brew "tree"
 brew "yarn"
+brew "fzf"
 
 cask "font-jetbrains-mono-nerd-font"
 cask "iterm2"
